
all:
	gcc -o sdl1_demo sdl1_demo.cpp -lSDL
	gcc -o sdl2_demo sdl2_demo.cpp -lSDL2
	gcc -o sdl2_demo2 sdl2_demo2.cpp -lSDL2
	gcc -o sdl2_demo3 sdl2_demo3.cpp -lSDL2

test:
	./sdl1_demo

clean:
	rm sdl1_demo sdl2_demo sdl2_demo2 sdl2_demo3
